### PR TITLE
Added ManrajGrover to user.json

### PR DESCRIPTION
**Pull request by ManrajGrover**
Please review and merge.

### CODE REVIEW

**Comment by debloper** [comment]
Thanks for adding yourself.
Please note, there is some issue with the Mozillians API recently - your data may not reflect on site yet.

**Comment by ManrajGrover** [comment]
Oh okay!

By when will it be fixed, any idea?

**Comment by debloper** [comment]
Nothing solid, sorry! :(

**Comment by ManrajGrover** [comment]
Hi @debloper :)

Its been more than a month and a half. May I know when can I see myself on the leaderboard? :)

**Pull request merged**
